@ Level 1b
Feature: Advanced scoring
  Player should be able to roll die and score under complicated situations - full chest

  @ Row 109
  Scenario: FC 2 swords, die on first roll   => lose 300 points
    Given The game is in progress......
    When Player with name "Kim" plays the game......
    When Player has 1000 points
    When Player draws two swords sea battle FC
    When Player rolls die with three skulls and five golds
    Then Player dies with three skulls and sees "Dead with 3 skulls. End of the turn."..
    Then Player sees "Battle lost, -300 pts" and scores 700 and closes connection...
  
  @ Row 110
  Scenario: FC 3 swords, die on first roll   => lose 500 points
    Given The game is in progress......
    When Player with name "Kim" plays the game......
    When Player has 1000 points
    When Player draws three swords sea battle FC
    When Player rolls die with three skulls and five golds
    Then Player dies with three skulls and sees "Dead with 3 skulls. End of the turn."..
    Then Player sees "Battle lost, -500 pts" and scores 500 and closes connection...
  
  @ Row 111
  Scenario: FC 4 swords, die on first roll   => lose 1000 points
    Given The game is in progress......
    When Player with name "Kim" plays the game......
    When Player has 1500 points
    When Player draws four swords sea battle FC
    When Player rolls die with three skulls and five golds
    Then Player dies with three skulls and sees "Dead with 3 skulls. End of the turn."..
    Then Player sees "Battle lost, -1000 pts" and scores 500 and closes connection...
  
  @ Row 112
  Scenario: show deduction received cannot make your score negative
    Given The game is in progress......
    When Player with name "Kim" plays the game......
    When Player has 500 points
    When Player draws four swords sea battle FC
    When Player rolls die with three skulls and five golds
    Then Player dies with three skulls and sees "Dead with 3 skulls. End of the turn."..
    Then Player sees "Battle lost, -1000 pts" and scores 0 and closes connection...
  
  @ Row 113
  Scenario: FC 2 swords, roll 3 monkeys 2 swords, 1 coin, 2 parrots  SC = 100 + 100 + 300 = 500
    Given The game is in progress......
    When Player with name "Kim" plays the game......
    When Player draws two swords sea battle FC
    When Player rolls die with three monkeys, two swords, one coin and two parrots
    When Player sees action menu and enters menu option 3.....
    Then Player sees "Battle win, +300 pts" and scores 500 and closes connection...
  
  @ Row 114
  Scenario: FC 2 swords, roll 4 monkeys 1 sword, 1 skull  2 parrots
  then reroll 2 parrots and get 1 sword and 1 skull   SC = 200 +  300 = 500
    Given The game is in progress......
    When Player with name "Kim" plays the game......
    When Player draws two swords sea battle FC
    When Player rolls die with four monkeys, one swords, one skull and two parrots
    When Player sees action menu and enters menu option 1.....
    When Player holds four monkeys and one sword and rerolls one sword and one skull
    When Player sees action menu and enters menu option 3.....
    Then Player sees "Battle win, +300 pts" and scores 500 and closes connection...
  
  @ Row 116
  Scenario: FC 3 swords, roll 3 monkeys 4 swords  SC = 100 + 200 + 500 = 800
    Given The game is in progress......
    When Player with name "Kim" plays the game......
    When Player draws three swords sea battle FC
    When Player rolls die with three monkeys, four swords and one parrot
    When Player sees action menu and enters menu option 3.....
    Then Player sees "Battle win, +500 pts" and scores 800 and closes connection...
  
  @ Row 117
  Scenario: FC 3 swords, roll 4 monkeys 2 swords 2 skulls
  then reroll 4 monkeys and get  2 skulls and 2 swords   -> DIE
    Given The game is in progress......
    When Player with name "Kim" plays the game......
    When Player has 1000 points
    When Player draws three swords sea battle FC
    When Player rolls die with four monkeys, two swords and two skulls
    When Player sees action menu and enters menu option 1.....
    When Player holds two swords and rerolls two skulls and two swords
    Then Player sees "Battle lost, -500 pts" and scores 500 and closes connection...
  
  @ Row 119
  Scenario: FC 4 swords, roll 3 monkeys 4 swords 1 skull  SC = 100 +200 + 1000 = 1300
    Given The game is in progress......
    When Player with name "Kim" plays the game......
    When Player draws four swords sea battle FC
    When Player rolls die with three monkeys, four swords and one skull
    When Player sees action menu and enters menu option 3.....
    Then Player sees "Battle win, +1000 pts" and scores 1300 and closes connection...
  
  @ Row 120
  Scenario: FC 4 swords, roll 3 monkeys, 1 sword, 1 skull, 1 diamond, 2 parrots
  then reroll 2 parrots and get 2 swords thus you have 3 monkeys, 3 swords, 1 diamond, 1 skull
  then reroll 3 monkeys and get  1 sword and 2 parrots  SC = 200 + 100 + 1000 = 1300
    Given The game is in progress......
    When Player with name "Kim" plays the game......
    When Player draws four swords sea battle FC
    When Player rolls die with three monkeys, one sword, one skull, one diamond and two parrots
    When Player sees action menu and enters menu option 1.....
    When Player holds three monkeys, one sword and one diamond and rerolls two swords
    When Player sees action menu and enters menu option 1.....
    When Player holds three swords, one diamond and rerolls one sword and two parrots
    When Player sees action menu and enters menu option 3.....
    Then Player sees "Battle Win, +1000 pts" and scores 1300 and closes connection...
